#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
set -e

# Prepare the runtime
[ -d $OPENSHIFT_DATA_DIR/go ] ||
    curl  http://go.googlecode.com/files/go.go1.linux-amd64.tar.gz |
    tar -xzf - -C $OPENSHIFT_DATA_DIR
curl http://gogs.dn.qbox.me/gogs_v0.6.9_linux_amd64.zip | tar -xf - -C $OPENSHIFT_DATA_DIR
export GOROOT=$OPENSHIFT_DATA_DIR/go
export PATH=$PATH:$GOROOT/bin

cd $OPENSHIFT_DATA_DIR
pwd
#cd hello
#go build
