#!/bin/bash
# The logic to start up your application should be put in this
# script. 
set -e

# Prepare the runtime
# that is not required for who won't build from sources,
# you can make it empty so it will never download afterwards
GO_PATH=go
GO_PATH=$OPENSHIFT_DATA_DIR$GO_PATH
[ -d $GO_PATH ] ||
    curl https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz |
tar -xzf - -C $OPENSHIFT_DATA_DIR
# end Prepare the runtime
# Prepare the gogs
cd $OPENSHIFT_DATA_DIR
# edit here if you got a better version
download_url=https://github.com/gogits/gogs/releases/download/v0.11.19/linux_amd64.zip
wget $download_url -O temp.zip; unzip -o temp.zip; rm temp.zip
if [ ! -f $OPENSHIFT_DATA_DIR/gogs/custom/conf/app.ini ];
then
    cd gogs
    mkdir -p custom/conf
    wget https://raw.githubusercontent.com/gogits/gogs/master/conf/app.ini -O custom/conf/app.ini
    echo "edit it after"
    sed -i "s/^DOMAIN.*/DOMAIN = $OPENSHIFT_APP_DNS/g" custom/conf/app.ini 
    sed -i "s/^HTTP_ADDR.*/HTTP_ADDR = $OPENSHIFT_DIY_IP/g" custom/conf/app.ini 
    sed -i "s/^HTTP_PORT.*/HTTP_PORT = $OPENSHIFT_DIY_PORT/g" custom/conf/app.ini 
    sed -i "s/^DISABLE_SSH.*/DISABLE_SSH = true/g" custom/conf/app.ini
    echo "mysql $OPENSHIFT_MYSQL_DB_URL user:password@host:port"
fi
# if want edit more
# vi $OPENSHIFT_DATA_DIR/gogs/custom/conf/app.ini  
# end Prepare gogs
export GOROOT=$OPENSHIFT_DATA_DIR/go
export PATH=$PATH:$GOROOT/bin
export HOME=$OPENSHIFT_DATA_DIR
export USERNAME=$OPENSHIFT_APP_UUID
cd $HOME/gogs
HOME=$OPENSHIFT_DATA_DIR nohup $OPENSHIFT_DATA_DIR/gogs/gogs web >>$OPENSHIFT_DATA_DIR/gogs/err.log 2>&1 & echo $! > $OPENSHIFT_DATA_DIR/gogs/run.pid 
exit

