#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.
if [ ! -f "$OPENSHIFT_DATA_DIR/gogs/run.pid" ]
then
    client_result "Application is already stopped"
else
    kill -9 `cat $OPENSHIFT_DATA_DIR/gogs/run.pid`
    rm $OPENSHIFT_DATA_DIR/gogs/run.pid
fi
